const express = require('express')
const cors = require('cors')
const app = express()
const config = require('./utils/config')
const usersRouter = require('./routers/users')
const tagsRouter = require('./routers/tags')
const loginRouter = require('./routers/login')
const middleware = require('./utils/middleware')
const verifyRouter = require('./routers/verify')
const resetRouter = require('./routers/reset')
const photosRouter = require('./routers/photos')
const mapRouter = require('./routers/map')
const likeRouter = require('./routers/likes')
const likeunlikeDisplayRouter = require('./routers/likeDisplay')
const reportRouter = require('./routers/report')
const blockRouter = require('./routers/block')

app.use(express.json({limit: '10mb', extended: true}))
app.use(express.urlencoded({limit: '10mb', extended: true}))
app.use(cors())
app.use(middleware.requestLogger)
app.enable('trust proxy')

app.use('/users', usersRouter)
app.use('/tags', tagsRouter)
app.use('/login', loginRouter)
app.use('/verify', verifyRouter)
app.use('/reset', resetRouter)
app.use('/photos', photosRouter)
app.use('/map', mapRouter)
app.use('/likes', likeRouter)
app.use('/likeDisplay', likeunlikeDisplayRouter)
app.use('/report', reportRouter)
app.use('/block', blockRouter)

app.use(middleware.unknownEndpoint)

app.listen(config.PORT, () => {
	console.log(`App running on port ${config.PORT}.`)
})