POST http://localhost:3001/users
Content-Type: application/json

{
	"firstName": "ulla",
	"lastName": "taalasmaa",
	"username": "ullaboo",
	"email": "ulla@ulla",
	"password": "pulla",
	"token": "oirhafjraglkf4802945",
	"birthdate": "1990-01-23"
}