POST http://localhost:3001/users
Content-Type: application/json

{
	"firstName": "ulla",
	"lastName": "taalasmaa",
	"username": "ulla2",
	"email": "ulla2@ulla",
	"password": "pulla",
	"token": "oirhafjraglkf4802945"
}