POST http://localhost:3001/users
Content-Type: application/json

{
	"firstName": "elli",
	"lastName": "t",
	"username": "ullaboo",
	"email": "elli@ulla",
	"password": "pulla",
	"token": "oirhafjraglkf4802945",
	"birthdate": "1990-01-23"
}