PUT http://localhost:3001/users/1
Content-Type: application/json

{
	"firstName": "ville",
	"lastName": "kalle",
	"email": "ulla@ulla",
	"gender": "male",
	"orientation": "m",
	"tags": "#hot#hip",
	"bio": ""
}